# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel Smith
email: dan@dansmith65.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.dansmith65.com" # the base hostname & protocol for your site
twitter_username: dansmith65
github_username:  dansmith65
safe: true
timezone: America/Phoenix

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE

# NOTE: this feature was disabled when updating to Jekyll 3.3
#       consider enabling it again once the new theme is worked out
# Compress HTML settings
# http://jch.penibelst.de/
# compress_html:
#   clippings: all
#   comments:  all
#   endings:   all
#   profile: false

# Compress CSS
# https://jekyllrb.com/docs/assets/
sass:
  style: compressed

# Front Matter defaults
# https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:year/:slug.html"
      layout: post
      author: Daniel Smith
      comments: true
      comments_locked: false

date_format: '%F'
date_time_format: '%F at %l:%M %p'
