# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel Smith
email: dan@dansmith65.com
description: A personal website of miscellany
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.dansmith65.com" # the base hostname & protocol for your site
author: dansmith65
twitter:
  username: dansmith65  # used by seo plugin
github_username:  dansmith65
    # If "github" exists as a setting, then github-metadata plugin populates it,
    # which adds about 8 seconds to the build time.
    # That's why I don't structure the github username the same way as twitter
repository: dansmith65/dansmith65.github.io
social:
  links:
    - https://twitter.com/dansmith65
    - https://www.facebook.com/dansmith65
    - https://www.linkedin.com/in/dansmith65
    - https://plus.google.com/+dansmith6565
    - https://github.com/dansmith65
google_site_verification: sD4H3EW3zsbZYbJKIsOHvGkgxUSpWHwthv_xmItCvLI
timezone: America/Phoenix
date_format: '%F'
date_time_format: '%F at %l:%M %p'
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE

# NOTE: this feature was disabled when updating to Jekyll 3.3
#       consider enabling it again once the new theme is worked out
# Compress HTML settings
# http://jch.penibelst.de/
# compress_html:
#   clippings: all
#   comments:  all
#   endings:   all
#   profile: false

# Compress CSS
# https://jekyllrb.com/docs/assets/
sass:
  style: compressed


collections:
  posts_by_year:
    output: true
    permalink: "/blog/:name/"
  posts_by_tag:
    output: true
    permalink: "/blog/tags/:name/"


# Front Matter defaults
# https://jekyllrb.com/docs/configuration/#front-matter-defaults
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:year/:slug.html"
      layout: post
      author: dansmith65
      comments: true
      comments_locked: false
  -
    scope:
      path: ""
      type: "posts_by_year"
    values:
      layout: posts_by_year
      description: List of posts in a year
  -
    scope:
      path: ""
      type: "posts_by_tag"
    values:
      layout: posts_by_tag
      description: List of posts with a tag

